"""add_constraints_and_indexes

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-25

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: ix_contact_messages_created, ix_service_requests_created,
    # ix_service_requests_status, and ix_service_translations_locale are
    # intentionally left untouched here. Alembic's autogenerate flagged them
    # as "removed" only because the SQLAlchemy models never declared
    # index=True on those columns -- they are legitimate, useful indexes
    # created directly in migration 0002 and must not be dropped.
    op.drop_constraint('contact_messages_service_id_fkey', 'contact_messages', type_='foreignkey')
    op.create_foreign_key(None, 'contact_messages', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_district_translations_district_locale', 'district_translations', type_='unique')
    op.create_unique_constraint('uq_district_translation', 'district_translations', ['district_id', 'locale'])
    op.create_index('ix_service_requests_service_id', 'service_requests', ['service_id'], unique=False)
    op.drop_constraint('service_requests_service_id_fkey', 'service_requests', type_='foreignkey')
    op.drop_constraint('service_requests_district_id_fkey', 'service_requests', type_='foreignkey')
    op.drop_constraint('service_requests_technician_id_fkey', 'service_requests', type_='foreignkey')
    op.create_foreign_key(None, 'service_requests', 'districts', ['district_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'service_requests', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'service_requests', 'technicians', ['technician_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_service_translations_service_locale', 'service_translations', type_='unique')
    op.create_unique_constraint('uq_service_translation', 'service_translations', ['service_id', 'locale'])
    op.drop_constraint('uq_technician_districts_tech_district', 'technician_districts', type_='unique')
    op.create_unique_constraint('uq_technician_district', 'technician_districts', ['technician_id', 'district_id'])
    op.drop_constraint('uq_technician_services_tech_service', 'technician_services', type_='unique')
    op.create_unique_constraint('uq_technician_service', 'technician_services', ['technician_id', 'service_id'])
    op.drop_constraint('uq_technician_translations_tech_locale', 'technician_translations', type_='unique')
    op.create_unique_constraint('uq_technician_translation', 'technician_translations', ['technician_id', 'locale'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_technician_translation', 'technician_translations', type_='unique')
    op.create_unique_constraint('uq_technician_translations_tech_locale', 'technician_translations', ['technician_id', 'locale'])
    op.drop_constraint('uq_technician_service', 'technician_services', type_='unique')
    op.create_unique_constraint('uq_technician_services_tech_service', 'technician_services', ['technician_id', 'service_id'])
    op.drop_constraint('uq_technician_district', 'technician_districts', type_='unique')
    op.create_unique_constraint('uq_technician_districts_tech_district', 'technician_districts', ['technician_id', 'district_id'])
    op.drop_constraint('uq_service_translation', 'service_translations', type_='unique')
    op.create_unique_constraint('uq_service_translations_service_locale', 'service_translations', ['service_id', 'locale'])
    op.drop_constraint('service_requests_service_id_fkey', 'service_requests', type_='foreignkey')
    op.drop_constraint('service_requests_district_id_fkey', 'service_requests', type_='foreignkey')
    op.drop_constraint('service_requests_technician_id_fkey', 'service_requests', type_='foreignkey')
    op.create_foreign_key('service_requests_technician_id_fkey', 'service_requests', 'technicians', ['technician_id'], ['id'])
    op.create_foreign_key('service_requests_district_id_fkey', 'service_requests', 'districts', ['district_id'], ['id'])
    op.create_foreign_key('service_requests_service_id_fkey', 'service_requests', 'services', ['service_id'], ['id'])
    op.drop_index('ix_service_requests_service_id', table_name='service_requests')
    op.drop_constraint('uq_district_translation', 'district_translations', type_='unique')
    op.create_unique_constraint('uq_district_translations_district_locale', 'district_translations', ['district_id', 'locale'])
    op.drop_constraint('contact_messages_service_id_fkey', 'contact_messages', type_='foreignkey')
    op.create_foreign_key('contact_messages_service_id_fkey', 'contact_messages', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###
